# Generated by Django 3.1.2 on 2020-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='item_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_name',
            field=models.CharField(max_length=30),
        ),
    ]
