# Generated by Django 3.1.2 on 2020-10-12 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201012_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
